name: 'Test build image'
on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Build
            run: |
              docker build .
